name: Cache Data

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  cache-data:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl command
        run: curl --request GET --url 'https://coverguesser.jerryguerrero.com/api/CacheData?cache_token=${{secrets.CACHE_TOKEN}}'
